class NameData {
  final int id, position;
  final String name, meaning, imageSrc;

  NameData({
    this.id,
    this.position,
    this.name,
    this.meaning,
    this.imageSrc,
  });
}

List<NameData> nameDatas = [
  NameData(
    id: 1,
    position: 1,
    name: "AR-RAHMAAN",
    meaning: "The Most or Entirely Merciful",
    imageSrc: "assets/images/1.jpg",
  ),
  NameData(
    id: 2,
    position: 2,
    name: "AR-RAHEEM",
    meaning: "The Bestower of Mercy",
    imageSrc: "assets/images/2.jpg",
  ),
  NameData(
    id: 3,
    position: 3,
    name: "AL-MALIK",
    meaning: "The King and Owner of Dominion",
    imageSrc: "assets/images/3.jpg",
  ),
  NameData(
    id: 4,
    position: 4,
    name: "AL-QUDDUS",
    meaning: "The Absolutely Pure",
    imageSrc: "assets/images/4.jpg",
  ),
  NameData(
    id: 5,
    position: 5,
    name: "AS-SALAM",
    meaning: "The Perfection and Giver of Peace",
    imageSrc: "assets/images/5.jpg",
  ),
  NameData(
    id: 6,
    position: 6,
    name: "AL-MU’MIN",
    meaning: "The One Who gives Emaan and Security",
    imageSrc: "assets/images/6.jpg",
  ),
  NameData(
    id: 7,
    position: 7,
    name: "AL-MUHAYMIN",
    meaning: "The Guardian, The Witness, The Overseer",
    imageSrc: "assets/images/7.jpg",
  ),
  NameData(
    id: 8,
    position: 8,
    name: "AL-AZEEZ",
    meaning: "The All Mighty",
    imageSrc: "assets/images/8.jpg",
  ),
  NameData(
    id: 9,
    position: 9,
    name: "AL-JABBAR",
    meaning: "The Compeller, The Restorer",
    imageSrc: "assets/images/9.jpg",
  ),
  NameData(
    id: 10,
    position: 10,
    name: "AL-MUTAKABBIR",
    meaning: "The Supreme, The Majestic",
    imageSrc: "assets/images/10.jpg",
  ),
  NameData(
    id: 11,
    position: 11,
    name: "AL-KHAALIQ",
    meaning: "The Creator, The Maker",
    imageSrc: "assets/images/11.jpg",
  ),
  NameData(
    id: 12,
    position: 12,
    name: "AL-BAARI’",
    meaning: "The Originator",
    imageSrc: "assets/images/12.jpg",
  ),
  NameData(
    id: 13,
    position: 13,
    name: "AL-MUSAWWIR",
    meaning: "The Fashioner",
    imageSrc: "assets/images/13.jpg",
  ),
  NameData(
    id: 14,
    position: 14,
    name: "AL-GHAFFAR",
    meaning: "The All- and Oft-Forgiving",
    imageSrc: "assets/images/14.jpg",
  ),
  NameData(
    id: 15,
    position: 15,
    name: "AL-QAHHARR",
    meaning: "The Subduer, The Ever-Dominating",
    imageSrc: "assets/images/15.jpg",
  ),
  NameData(
    id: 16,
    position: 16,
    name: "AL-WAHHAAB",
    meaning: "The Giver of Gifts",
    imageSrc: "assets/images/16.jpg",
  ),
  NameData(
    id: 17,
    position: 17,
    name: "AR-RAZZAAQ",
    meaning: "The Provider",
    imageSrc: "assets/images/17.jpg",
  ),
  NameData(
    id: 18,
    position: 18,
    name: "AL-FATTAAH",
    meaning: "The Opener, The Judger",
    imageSrc: "assets/images/18.jpg",
  ),
  NameData(
    id: 19,
    position: 19,
    name: "AL-‘ALEEM",
    meaning: "The All-Knowing, The Omniscient",
    imageSrc: "assets/images/19.jpg",
  ),
  NameData(
    id: 20,
    position: 20,
    name: "AL-QAABID",
    meaning: "The Withholder",
    imageSrc: "assets/images/20.jpg",
  ),
  NameData(
    id: 21,
    position: 21,
    name: "AL-BAASIT",
    meaning: "The Extender",
    imageSrc: "assets/images/21.jpg",
  ),
  NameData(
    id: 22,
    position: 22,
    name: "AL-KHAAFIDH",
    meaning: "The Reducer, The Abaser",
    imageSrc: "assets/images/22.jpg",
  ),
  NameData(
    id: 23,
    position: 23,
    name: "AR-RAAFI’",
    meaning: "The Exalter, The Elevator",
    imageSrc: "assets/images/23.jpg",
  ),
  NameData(
    id: 24,
    position: 24,
    name: "AL-MU’IZZ",
    meaning: "The Honourer, The Bestower",
    imageSrc: "assets/images/24.jpg",
  ),
  NameData(
    id: 25,
    position: 25,
    name: "AL-MUZILD",
    meaning: "The Dishonourer, The Humiliator",
    imageSrc: "assets/images/25.jpg",
  ),
  NameData(
    id: 26,
    position: 26,
    name: "AS-SAMEE’",
    meaning: "The All-Hearing",
    imageSrc: "assets/images/26.jpg",
  ),
  NameData(
    id: 27,
    position: 27,
    name: "AL-BASEER",
    meaning: "The All-Seeing",
    imageSrc: "assets/images/27.jpg",
  ),
  NameData(
    id: 28,
    position: 28,
    name: "AL-HAKAM",
    meaning: "The Judge, The Giver of Justice",
    imageSrc: "assets/images/28.jpg",
  ),
  NameData(
    id: 29,
    position: 29,
    name: "AL-‘ADL",
    meaning: "The Utterly Justr",
    imageSrc: "assets/images/29.jpg",
  ),
  NameData(
    id: 30,
    position: 30,
    name: "AL-LATEEF",
    meaning: "The Subtle One, The Most Gentle",
    imageSrc: "assets/images/30.jpg",
  ),
  NameData(
    id: 31,
    position: 31,
    name: "AL-KHABEER",
    meaning: "The Acquainted, the All-Aware",
    imageSrc: "assets/images/31.jpg",
  ),
  NameData(
    id: 32,
    position: 32,
    name: "AL-HALEEM",
    meaning: "The Most Forbearing",
    imageSrc: "assets/images/32.jpg",
  ),
  NameData(
    id: 33,
    position: 33,
    name: "AL-‘ATHEEM",
    meaning: "The Magnificent, The Supreme",
    imageSrc: "assets/images/33.jpg",
  ),
  NameData(
    id: 34,
    position: 34,
    name: "AL-GHAFOOR",
    meaning: "The Forgiving, The Exceedingly Forgiving",
    imageSrc: "assets/images/34.jpg",
  ),
  NameData(
    id: 35,
    position: 35,
    name: "ASH-SHAKOOR",
    meaning: "The Most Appreciative",
    imageSrc: "assets/images/35.jpg",
  ),
  NameData(
    id: 36,
    position: 36,
    name: "AL-‘ALEE",
    meaning: "The Most High, The Exalted",
    imageSrc: "assets/images/36.jpg",
  ),
  NameData(
    id: 37,
    position: 37,
    name: "AL-KABEER",
    meaning: "The Greatest, The Most Grand",
    imageSrc: "assets/images/37.jpg",
  ),
  NameData(
    id: 38,
    position: 38,
    name: "AL-HAFEEDH",
    meaning: "The Preserver, The All-Heedful and All-Protecting",
    imageSrc: "assets/images/38.jpg",
  ),
  NameData(
    id: 39,
    position: 39,
    name: "AL-MUQEET",
    meaning: "The Sustainer",
    imageSrc: "assets/images/39.jpg",
  ),
  NameData(
    id: 40,
    position: 40,
    name: "AL-HASEEB",
    meaning: "The Reckoner, The Sufficient",
    imageSrc: "assets/images/40.jpg",
  ),
  NameData(
    id: 41,
    position: 41,
    name: "AL-JALEEL",
    meaning: "The Majestic",
    imageSrc: "assets/images/41.jpg",
  ),
  NameData(
    id: 42,
    position: 42,
    name: "AL-KAREEM",
    meaning: "The Most Generous, The Most Esteemed",
    imageSrc: "assets/images/42.jpg",
  ),
  NameData(
    id: 43,
    position: 43,
    name: "AR-RAQEEB",
    meaning: "The Watchful",
    imageSrc: "assets/images/43.jpg",
  ),
  NameData(
    id: 44,
    position: 44,
    name: "AL-MUJEEB",
    meaning: "The Responsive One",
    imageSrc: "assets/images/44.jpg",
  ),
  NameData(
    id: 45,
    position: 45,
    name: "AL-WAASI’",
    meaning: "The All-Encompassing, the Boundless",
    imageSrc: "assets/images/45.jpg",
  ),
  NameData(
    id: 46,
    position: 46,
    name: "AL-HAKEEMB",
    meaning: "The All-Wise",
    imageSrc: "assets/images/46.jpg",
  ),
  NameData(
    id: 47,
    position: 47,
    name: "AL-WADOOD",
    meaning: "The Most Loving",
    imageSrc: "assets/images/47.jpg",
  ),
  NameData(
    id: 48,
    position: 48,
    name: "AL-MAJEED",
    meaning: "The Glorious, The Most Honorable",
    imageSrc: "assets/images/48.jpg",
  ),
  NameData(
    id: 49,
    position: 49,
    name: "AL-BA’ITH",
    meaning: "The Resurrector, The Raiser of the Dead",
    imageSrc: "assets/images/49.jpg",
  ),
  NameData(
    id: 50,
    position: 50,
    name: "ASH-SHAHEED",
    meaning: "The All- and Ever Witnessing",
    imageSrc: "assets/images/50.jpg",
  ),
  NameData(
    id: 51,
    position: 51,
    name: "AL-HAQQ",
    meaning: "The Absolute Truth",
    imageSrc: "assets/images/51.jpg",
  ),
  NameData(
    id: 52,
    position: 52,
    name: "AL-WAKEEL",
    meaning: "The Trustee, The Disposer of Affairs",
    imageSrc: "assets/images/52.jpg",
  ),
  NameData(
    id: 53,
    position: 53,
    name: "AL-QAWIYY",
    meaning: "The All-Strong",
    imageSrc: "assets/images/53.jpg",
  ),
  NameData(
    id: 54,
    position: 54,
    name: "AL-MATEEN",
    meaning: "The Firm, The Steadfast",
    imageSrc: "assets/images/54.jpg",
  ),
  NameData(
    id: 55,
    position: 55,
    name: "AL-WALIYY",
    meaning: "The Protecting Associate",
    imageSrc: "assets/images/55.jpg",
  ),
  NameData(
    id: 56,
    position: 56,
    name: "AL-HAMEED",
    meaning: "The Praiseworthy",
    imageSrc: "assets/images/56.jpg",
  ),
  NameData(
    id: 57,
    position: 57,
    name: "AL-MUHSEE",
    meaning: "The All-Enumerating, The Counter",
    imageSrc: "assets/images/57.jpg",
  ),
  NameData(
    id: 58,
    position: 58,
    name: "AL-MUBDI",
    meaning: "The Originator, The Initiator",
    imageSrc: "assets/images/58.jpg",
  ),
  NameData(
    id: 59,
    position: 59,
    name: "AL-MU’ID",
    meaning: "	The Restorer, The Reinstater",
    imageSrc: "assets/images/59.jpg",
  ),
  NameData(
    id: 60,
    position: 60,
    name: "AL-MUHYEEEB",
    meaning: "The Giver of Lifet",
    imageSrc: "assets/images/60.jpg",
  ),
  NameData(
    id: 61,
    position: 61,
    name: "AL-MUMEET",
    meaning: "The Bringer of Death, the Destroyer",
    imageSrc: "assets/images/61.jpg",
  ),
  NameData(
    id: 62,
    position: 62,
    name: "AL-HAYY",
    meaning: "The Ever-Living",
    imageSrc: "assets/images/62.jpg",
  ),
  NameData(
    id: 63,
    position: 63,
    name: "AL-QAYYOOM",
    meaning: "The Sustainer, The Self-Subsisting",
    imageSrc: "assets/images/63.jpg",
  ),
  NameData(
    id: 64,
    position: 64,
    name: "AL-WAAJID",
    meaning: "The Perceiver",
    imageSrc: "assets/images/64.jpg",
  ),
  NameData(
    id: 65,
    position: 65,
    name: "AL-MAAJID",
    meaning: "The Illustrious, the Magnificent",
    imageSrc: "assets/images/65.jpg",
  ),
  NameData(
    id: 66,
    position: 66,
    name: "AL-WAAHID",
    meaning: "The One",
    imageSrc: "assets/images/66.jpg",
  ),
  NameData(
    id: 67,
    position: 67,
    name: "AL-AHAD",
    meaning: "The Unique, The Only One",
    imageSrc: "assets/images/67.jpg",
  ),
  NameData(
    id: 68,
    position: 68,
    name: "AS-SAMADB",
    meaning: "The Eternal, Satisfier of Needs",
    imageSrc: "assets/images/68.jpg",
  ),
  NameData(
    id: 69,
    position: 69,
    name: "AL-QADIR",
    meaning: "The Capable, The Powerful",
    imageSrc: "assets/images/69.jpg",
  ),
  NameData(
    id: 70,
    position: 70,
    name: "AL-MUQTADIR",
    meaning: "The Omnipotent",
    imageSrc: "assets/images/70.jpg",
  ),
  NameData(
    id: 71,
    position: 71,
    name: "AL-MUQADDIM",
    meaning: "The Expediter, The Promoter",
    imageSrc: "assets/images/71.jpg",
  ),
  NameData(
    id: 72,
    position: 72,
    name: "AL-MU’AKHKHIR",
    meaning: "The Delayer, the Retarder",
    imageSrc: "assets/images/72.jpg",
  ),
  NameData(
    id: 73,
    position: 73,
    name: "AL-AWWAL",
    meaning: "The First",
    imageSrc: "assets/images/73.jpg",
  ),
  NameData(
    id: 74,
    position: 74,
    name: "AL-AAKHIR",
    meaning: "The Last",
    imageSrc: "assets/images/74.jpg",
  ),
  NameData(
    id: 75,
    position: 75,
    name: "AZ-DHAAHIR",
    meaning: "The Manifest",
    imageSrc: "assets/images/75.jpg",
  ),
  NameData(
    id: 76,
    position: 76,
    name: "AL-BAATIN",
    meaning: "The Hidden One, Knower of the Hidden",
    imageSrc: "assets/images/76.jpg",
  ),
  NameData(
    id: 77,
    position: 77,
    name: "AL-WAALI",
    meaning: "The Governor, The Patron",
    imageSrc: "assets/images/77.jpg",
  ),
  NameData(
    id: 78,
    position: 78,
    name: "AL-MUTA’ALI",
    meaning: "The Self Exalted",
    imageSrc: "assets/images/78.jpg",
  ),
  NameData(
    id: 79,
    position: 79,
    name: "AL-BARR",
    meaning: "The Source of Goodness, the Kind Benefactor",
    imageSrc: "assets/images/79.jpg",
  ),
  NameData(
    id: 80,
    position: 80,
    name: "AT-TAWWAB",
    meaning: "The Ever-Pardoning, The Relenting",
    imageSrc: "assets/images/80.jpg",
  ),
  NameData(
    id: 81,
    position: 81,
    name: "AL-MUNTAQIM",
    meaning: "The Avenger",
    imageSrc: "assets/images/81.jpg",
  ),
  NameData(
    id: 82,
    position: 82,
    name: "AL-‘AFUWW",
    meaning: "The Pardoner",
    imageSrc: "assets/images/82.jpg",
  ),
  NameData(
    id: 83,
    position: 83,
    name: "AR-RA’OOF",
    meaning: "The Most Kind",
    imageSrc: "assets/images/83.jpg",
  ),
  NameData(
    id: 84,
    position: 84,
    name: "MAALIK-UL-MULK",
    meaning: "Master of the Kingdom, Owner of the Dominion",
    imageSrc: "assets/images/84.jpg",
  ),
  NameData(
    id: 85,
    position: 85,
    name: "DHUL-JALAALI WAL-IKRAAM",
    meaning: "Possessor of Glory and Honour, Lord of Majesty and Generosity",
    imageSrc: "assets/images/85.jpg",
  ),
  NameData(
    id: 86,
    position: 86,
    name: "AL-MUQSIT",
    meaning: "The Equitable, the Requiter",
    imageSrc: "assets/images/86.jpg",
  ),
  NameData(
    id: 87,
    position: 87,
    name: "AL-JAAMI’",
    meaning: "The Gatherer, the Uniter",
    imageSrc: "assets/images/87.jpg",
  ),
  NameData(
    id: 88,
    position: 88,
    name: "AL-GHANIYY",
    meaning: "The Self-Sufficient, The Wealthy",
    imageSrc: "assets/images/88.jpg",
  ),
  NameData(
    id: 89,
    position: 89,
    name: "AL-MUGHNI",
    meaning: "The Enricher",
    imageSrc: "assets/images/89.jpg",
  ),
  NameData(
    id: 90,
    position: 90,
    name: "AL-MANI’",
    meaning: "The Withholder",
    imageSrc: "assets/images/90.jpg",
  ),
  NameData(
    id: 91,
    position: 91,
    name: "	AD-DHARR",
    meaning: "The Distresser",
    imageSrc: "assets/images/91.jpg",
  ),
  NameData(
    id: 92,
    position: 92,
    name: "AN-NAFI’",
    meaning: "The Propitious, the Benefactor",
    imageSrc: "assets/images/92.jpg",
  ),
  NameData(
    id: 93,
    position: 93,
    name: "AN-NUR",
    meaning: "The Light, The Illuminator",
    imageSrc: "assets/images/93.jpg",
  ),
  NameData(
    id: 94,
    position: 94,
    name: "AL-HAADI",
    meaning: "The Guide",
    imageSrc: "assets/images/94.jpg",
  ),
  NameData(
    id: 95,
    position: 95,
    name: "AL-BADEE’",
    meaning: "The Incomparable Originator",
    imageSrc: "assets/images/95.jpg",
  ),
  NameData(
    id: 96,
    position: 96,
    name: "AL-BAAQI",
    meaning: "The Ever-Surviving, The Everlasting",
    imageSrc: "assets/images/96.jpg",
  ),
  NameData(
    id: 97,
    position: 97,
    name: "AL-WAARITH",
    meaning: "The Inheritor, The Heirr",
    imageSrc: "assets/images/97.jpg",
  ),
  NameData(
    id: 98,
    position: 98,
    name: "AR-RASHEED",
    meaning: "The Guide, Infallible Teacher",
    imageSrc: "assets/images/98.jpg",
  ),
  NameData(
    id: 99,
    position: 99,
    name: "AS-SABOOR",
    meaning: "The Forbearing, The Patient",
    imageSrc: "assets/images/99.jpg",
  ),
];
